const $=s=>document.querySelector(s), money=n=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(galaxy|moto|motorola|mt|samsung|xiaomi|redmi)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
let brand='',limit=24, filtered=[];const selected=new Map(),comparison=new Map();
const cheapest=p=>p.variants.reduce((a,b)=>a.price<=b.price?a:b);
const variant=p=>p.variants.find(v=>v.id===selected.get(p.id))||cheapest(p);
const wa=(p,v)=>'https://wa.me/5511915068682?text='+encodeURIComponent(`Olá! Gostaria de confirmar a troca de tela: ${p.model.toLowerCase().startsWith(p.brand.toLowerCase())?'':p.brand+' '}${p.model}, linha ${p.line}, ${v.name}. ${v.originalPrice?'Oferta no Pix':'Estimativa do site'}: ${money(v.price)}, com instalação e película. Pode confirmar compatibilidade e disponibilidade?`);
function models(){const old=$('#model').value;$('#model').innerHTML='<option value="">Todos os modelos</option>'+[...new Set(CATALOG.filter(p=>!brand||p.brand===brand).map(p=>p.model))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true})).map(m=>`<option>${esc(m)}</option>`).join('');$('#model').value=old;}
function brands(){const priority=['Samsung','Motorola','iPhone','Xiaomi'];const names=[...new Set(CATALOG.map(p=>p.brand))].sort((a,b)=>(priority.includes(a)?priority.indexOf(a):99)-(priority.includes(b)?priority.indexOf(b):99)||a.localeCompare(b));$('#brands').innerHTML=['',...names].map(b=>`<button type="button" data-brand="${esc(b)}" aria-pressed="${brand===b}">${esc(b||'Todas as marcas')}</button>`).join(''); }
const promotion=v=>v.originalPrice?`<div class="offer-line"><span class="offer-badge">${Math.floor((v.originalPrice-v.price)*100/v.originalPrice)}% OFF no Pix</span><span>De <s>${money(v.originalPrice)}</s></span></div>`:'';
function card(p){const v=variant(p);return `<article class="product ${v.originalPrice?'on-sale':''}"><div class="card-top"><span>${esc(p.brand)}</span><span class="badge">${esc(p.type)}</span></div><h3>${esc(p.model)}</h3><p class="line">Linha: ${esc(p.line)}</p>${p.needsCheck?'<p class="check">Exige avaliação da peça e do procedimento</p>':''}<label class="variant-label">Montagem<select data-variant="${p.id}" aria-label="Montagem de ${esc(p.model)}">${p.variants.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''}>${esc(x.name)}${x.price>Number($('#budget').value||Infinity)*100?' · acima do filtro':''}</option>`).join('')}</select></label>${promotion(v)}<div class="price">${money(v.price)}</div><p class="included">${v.originalPrice?`No Pix · economize ${money(v.originalPrice-v.price)}`:'Estimativa'} • instalação + película</p><a class="quote" href="${wa(p,v)}" target="_blank" rel="noopener noreferrer">Consultar esta opção ↗</a><button class="compare-toggle" data-compare="${p.id}" aria-pressed="${comparison.has(p.id)}">${comparison.has(p.id)?'✓ Na comparação':'+ Comparar opção'}</button></article>`;}
function render(){const raw=$('#search').value,q=normal(raw).split(' ').filter(Boolean),budget=Number($('#budget').value||Infinity)*100,inferred=/\b(galaxy|samsung)\b/i.test(raw)?'Samsung':/\b(moto|motorola)\b/i.test(raw)?'Motorola':/\b(xiaomi|redmi)\b/i.test(raw)?'Xiaomi':'';
filtered=CATALOG.filter(p=>{if($('#only-offers').checked&&!variant(p).originalPrice)return false;if(brand&&p.brand!==brand||inferred&&p.brand!==inferred||$('#model').value&&p.model!==$('#model').value||$('#type').value&&p.type!==$('#type').value)return false;const hay=normal([p.brand,p.model,p.sourceModel,p.line].join(' '));if(!q.every(t=>hay.includes(t)))return false;if(variant(p).price>budget){const fit=p.variants.find(v=>v.price<=budget);if(!fit)return false;selected.set(p.id,fit.id);}return true;});
filtered.sort((a,b)=>$('#sort').value==='price-asc'?variant(a).price-variant(b).price:$('#sort').value==='price-desc'?variant(b).price-variant(a).price:(a.brand+' '+a.model).localeCompare(b.brand+' '+b.model,'pt-BR',{numeric:true}));
$('#products').innerHTML=filtered.slice(0,limit).map(card).join('');$('#count').textContent=`${filtered.length} opções de tela encontradas`;$('#shown').textContent=filtered.length?`Mostrando ${Math.min(limit,filtered.length)} de ${filtered.length}`:'';$('#more').hidden=filtered.length<=limit;$('#empty').hidden=filtered.length>0;$('#clear-search').hidden=!$('#search').value;}
function refresh(){limit=24;render();}function reset(){brand='';$('#only-offers').checked=false;selected.clear();for(const id of ['search','model','type','budget'])$('#'+id).value='';$('#sort').value='price-asc';brands();models();refresh();}
function compareBar(){ $('#compare-bar').hidden=!comparison.size;$('#compare-count').textContent=`${comparison.size} de 3 opções`; }
$('#brands').addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(!b)return;brand=b.dataset.brand;$('#model').value='';brands();models();refresh();});
$('#search').addEventListener('input',refresh);for(const id of ['model','type','budget','sort','only-offers'])$('#'+id).addEventListener('change',refresh);
$('#clear-search').onclick=()=>{$('#search').value='';refresh();$('#search').focus();};$('#reset').onclick=reset;$('#more').onclick=()=>{limit+=24;render();};
document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{reset();$('#search').value=b.dataset.search;refresh();});
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{reset();$('#type').value=b.dataset.type;refresh();$('#catalogo').scrollIntoView({behavior:'smooth'});});
$('#products').addEventListener('change',e=>{const id=e.target.dataset.variant;if(!id)return;selected.set(id,e.target.value);if(comparison.has(id))comparison.set(id,{p:CATALOG.find(p=>p.id===id),v:CATALOG.find(p=>p.id===id).variants.find(v=>v.id===e.target.value)});render();});
$('#products').addEventListener('click',e=>{const b=e.target.closest('[data-compare]');if(!b)return;const p=CATALOG.find(p=>p.id===b.dataset.compare);if(comparison.has(p.id))comparison.delete(p.id);else if(comparison.size<3)comparison.set(p.id,{p,v:variant(p)});else{ $('#notice').textContent='Você já escolheu 3 opções. Remova uma para adicionar outra.';b.textContent='Limite de 3 opções';return;}compareBar();render();});
$('#clear-compare').onclick=()=>{comparison.clear();compareBar();render();};$('#show-compare').onclick=()=>{$('#compare-content').innerHTML=[...comparison.values()].map(({p,v})=>`<article><span class="badge">${esc(p.type)}</span><h3>${esc(p.model)}</h3><p>${esc(p.brand)} · ${esc(p.line)}</p><p>${esc(v.name)}</p>${promotion(v)}<strong class="price">${money(v.price)}${v.originalPrice?' no Pix':''}</strong><a class="quote" href="${wa(p,v)}" target="_blank" rel="noopener noreferrer">Confirmar opção ↗</a></article>`).join('');$('#comparison').showModal();};$('#close-compare').onclick=()=>$('#comparison').close();
document.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>{reset();$('#budget').value=b.dataset.budget;refresh();$('#catalogo').scrollIntoView({behavior:'smooth'});});
$('#see-offers').onclick=()=>{reset();$('#only-offers').checked=true;refresh();$('#catalogo').scrollIntoView({behavior:'smooth'});};
$('#starting-price').textContent=money(Math.min(...CATALOG.map(p=>cheapest(p).price)));
brands();models();render();
