'use strict';
const catalog=window.CATALOG||[];
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const whatsapp=text=>'https://wa.me/5511915068682?text='+encodeURIComponent(text);
let brand='Todas',limit=24;
const selected=new Map();
document.querySelectorAll('[data-whatsapp]').forEach(a=>a.href=whatsapp('Olá, Peixoto Cell! Vim pelo catálogo e gostaria de um orçamento para uma tela.'));
const brands=[...new Set(catalog.map(p=>p.brand))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
brands.forEach(b=>$('brand').add(new Option(b,b)));
$('brand-directory').innerHTML=['Todas',...brands].map(b=>`<button class="chip ${b==='Todas'?'selected':''}" data-brand="${esc(b)}" aria-pressed="${b==='Todas'}">${esc(b)}</button>`).join('');
function updateModels(){ $('model').replaceChildren(new Option(brand==='Todas'?'Escolha uma marca primeiro':'Todos os modelos','Todas')); $('model').disabled=brand==='Todas'; if(brand!=='Todas') [...new Set(catalog.filter(p=>p.brand===brand).map(p=>p.model))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true})).forEach(m=>$('model').add(new Option(m,m))); }

function updateLines(){const previous=$('line').value;$('line').replaceChildren(new Option('Todas as linhas','Todas'));[...new Set(catalog.filter(p=>(brand==='Todas'||p.brand===brand)&&($('model').value==='Todas'||p.model===$('model').value)).map(p=>p.line))].sort().forEach(l=>$('line').add(new Option(l,l)));if([...$('line').options].some(o=>o.value===previous))$('line').value=previous;}
function filtered(){const terms=$('search').value.trim().split(/\s+/).map(normalize).filter(Boolean);let list=catalog.filter(p=>(brand==='Todas'||p.brand===brand)&&($('model').value==='Todas'||p.model===$('model').value)&&($('line').value==='Todas'||p.line===$('line').value)&&terms.every(t=>normalize(p.brand+' '+p.model+' '+p.line).includes(t)));const min=p=>Math.min(...p.variants.map(v=>v.price));switch($('sort').value){case'default':list.sort((a,b)=>a.brand.localeCompare(b.brand,'pt-BR')||a.model.localeCompare(b.model,'pt-BR',{numeric:true})||a.line.localeCompare(b.line,'pt-BR'));break;case'price-asc':list.sort((a,b)=>min(a)-min(b));break;case'price-desc':list.sort((a,b)=>min(b)-min(a));break;case'name':list.sort((a,b)=>(a.brand+' '+a.model).localeCompare(b.brand+' '+b.model,'pt-BR',{numeric:true}));}return list;}
function card(p){const idx=selected.get(p.id)||0;const v=p.variants[idx];const msg=`Olá, Peixoto Cell! Gostaria de um orçamento para a tela ${p.brand} ${p.model}, linha ${p.line}, ${v.name.toLowerCase()}. Valor de referência no catálogo: R$ ${money.format(v.price/100)}. Pode confirmar compatibilidade, disponibilidade e instalação?`;return `<article class="product-card" data-id="${p.id}"><div class="card-top"><span class="card-brand">${esc(p.brand)}</span><span class="screen-icon" aria-hidden="true"></span></div><p class="type-label">TELA PARA</p><h3>${esc(p.model)}</h3><span class="card-line">${esc(p.line)}</span><div class="variant-list" role="group" aria-label="Versão da tela ${esc(p.model)}">${p.variants.map((opt,i)=>`<button type="button" class="variant" data-variant="${i}" aria-pressed="${i===idx}">${esc(opt.name)}</button>`).join('')}</div><div class="price-row"><p class="price"><small>R$</small>${money.format(v.price/100)}</p><p class="price-note">Valor da tela<br>sob consulta de estoque</p></div><a class="quote" href="${esc(whatsapp(msg))}" target="_blank" rel="noopener noreferrer" aria-label="Pedir orçamento: ${esc(p.brand+' '+p.model+', '+p.line+', '+v.name)}">Pedir orçamento <span aria-hidden="true">↗</span></a></article>`;}
function render(){const list=filtered();let lastBrand='';$('products').innerHTML=list.slice(0,limit).map(p=>{const heading=$('sort').value==='default'&&p.brand!==lastBrand?`<h3 class="brand-heading">${esc(p.brand)} <span>Telas por modelo</span></h3>`:'';lastBrand=p.brand;return heading+card(p);}).join('');$('result-count').textContent=`${list.length} ${list.length===1?'opção de tela encontrada':'opções de telas encontradas'}`;$('shown-count').textContent=list.length?`Mostrando ${Math.min(limit,list.length)} de ${list.length} opções`:'';$('load-more').hidden=limit>=list.length;$('empty').hidden=list.length>0;$('clear-search').hidden=!$('search').value;}
function setBrand(value){brand=value;$('brand').value=value;document.querySelectorAll('[data-brand]').forEach(b=>{const active=b.dataset.brand===value;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});updateModels();$('line').value='Todas';updateLines();limit=24;render();}
$('search').addEventListener('input',()=>{limit=24;render();});$('clear-search').addEventListener('click',()=>{$('search').value='';limit=24;render();$('search').focus();});$('brand').addEventListener('change',e=>setBrand(e.target.value));document.querySelectorAll('[data-brand]').forEach(b=>b.addEventListener('click',()=>setBrand(b.dataset.brand)));['line','sort'].forEach(id=>$(id).addEventListener('change',()=>{limit=24;render();}));$('load-more').addEventListener('click',()=>{limit+=24;render();});$('reset').addEventListener('click',()=>{$('search').value='';$('line').value='Todas';$('sort').value='default';setBrand('Todas');$('search').focus();});
$('products').addEventListener('click',e=>{const b=e.target.closest('[data-variant]');if(!b)return;const article=b.closest('article');const id=article.dataset.id;const idx=Number(b.dataset.variant);selected.set(id,idx);article.outerHTML=card(catalog.find(p=>p.id===id));document.querySelector(`[data-id="${id}"] [data-variant="${idx}"]`).focus();});
$('model').addEventListener('change',()=>{$('line').value='Todas';updateLines();limit=24;render();});
$('year').textContent=new Date().getFullYear();updateModels();updateLines();render();
